#! /usr/bin/bash
shopt -s extglob 
<<COMMENT
select option in createDB SelectDB CreateTB exit
do
case $option in 
"createDB")
read -p "Please Enter Database name: " dbName
if [ -e $dbName ]
then
	echo "database is already exist"
else
	mkdir $dbName
	echo "Database is created successfully"
fi
;;
"SelectDB")
read -p "Please Enter Database name: " selectedDb
if [ -e $selectedDb ]
then
	cd $selectedDb
	echo "$selectedDb Database is selected"
else
	echo "Database is not exist"
fi
;;
"CreateTB")
read -p "Please enter table name: " tbName
if [ -e $tbName ]
then
	echo "table is already exist"
else
	read -p "please enter columns number to be created: " numCol
	pk=0
	for ((i=0;i<$numCol;i++))
	do
		line=""
		read -p "please enter column name: " colName
		line+=$colName
		read -p "please enter column Datatype (int/str): " colType
		line+=:$colType
		
		if [[ $pk -eq 0 ]]
		then
			read -p "Do you want to make this column pk (y/n): " checkPk
			if [[ "yes" =~ $checkPk ]]
			then
				line+=:PK
				pk=1
			fi	
		fi
		echo $line >> .$tbName"_metadata"
		
	done
	touch $tbName
	echo "table is created successfully"
fi
;;
esac
done






"ConnectDB")


"DropDB")


"Exit")
 
 
COMMENT
if [ -e ~/.local/bin/iti ]
then
	cd ~/.local/bin/iti
else
	mkdir ~/.local/bin/iti
	cd ~/.local/bin/iti
fi

select option in CreateDB ListDB ConnectDB DropDB Exit
do
case $option in 
"CreateDB")
read -p "Please Enter Database name: " dbName
if [ -e $dbName ]
then
	echo "database is already exist"
else
	mkdir $dbName
	echo "Database is created successfully"
fi
;;

"ListDB")
esac
done


